apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-2023mt03013
  labels:
    app: app-2023mt03013
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-2023mt03013
  template:
    metadata:
      labels:
        app: app-2023mt03013
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
        - name: app
          image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/img-2023mt03013:strict
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: config-2023mt03013
                  key: APP_VERSION
            - name: APP_TITLE
              valueFrom:
                configMapKeyRef:
                  name: config-2023mt03013
                  key: APP_TITLE
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /get_info
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /get_info
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
