apiVersion: v1
kind: Service
metadata:
  name: svc-2023mt03013
  labels:
    app: app-2023mt03013
spec:
  type: LoadBalancer
  selector:
    app: app-2023mt03013
  ports:
    - name: http
      port: 8000
      targetPort: 8000
